### PR TITLE
Splitting Plasma Contract into Base and Auction functionality

### PR DESCRIPTION
**Pull request by fleupold**
Everything that is just related to basic Plasma (deposit, transaction, exit) goes into Plasma.sol. The batch auction specific stuff is now in BatchAuctionPlasma.

I'm not super happy about having the BlockType in the Base Plasma, and am open for suggestions on how to work around that.

### CODE REVIEW

**Comment by fleupold** [comment]
Plasma.sol now has 100% line coverage, 88.9% branch coverage.

**Comment by bh2smith** [comment]
I think that submitBlock should only be the bare code without any of the block type constraints. The Block type should be in the PlasmaAuction.sol which contains an implementation of submitBlock that checks all the block type constraints and then calls **super**. 

Furthermore, I would like to suggest the name _PlasmaAuction_ or _PlasmaBatchAuction_ as opposed to having Plasma last.

In any case, none of my suggestions are overly important at the time being!

**Review by josojo — APPROVED** [review]
Good progress.

I am not concerned about having the blocktype in the plasma.sol at all. Later on, we need to add even more changes if the plasma chain reset to certain heights is implemented.
That is just what it is.

Still, this split improves readability.

**Comment by fleupold** [comment]
> Block type should be in the PlasmaAuction.sol which contains an implementation of submitBlock that checks all the block type constraints and then calls super.

Plasma.sol however needs tos tore the BlockType along with the block in its mapping. That means it must somehow "know" about BlockType, unless we want to pass an opaque uint that we later cast back into the BlockType.
I will leave it for now but carry out the renaming you suggested.

**Pull request merged**
